### ISSUE TITLE
Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.5.4/node-v57-darwin-x64-Release.tar.gz

### ISSUE THREAD

**Issue by asecondwill** [klokantech/tileserver-gl#216] opened 2017-09-24 14:06 UTC
I get this error installing locally.  

my setup is:

```
node -v
tileserver-gl ❯ node -v
v8.5.0
tileserver-gl ❯ npm -v
5.3.0
```

and I'm on OSX sierra.

**Comment by petrsloup** [comment] 2017-09-25 11:23
You need to use node v6

Duplicate of #213

**Closed by petrsloup** 2017-09-25 11:23 UTC
