### ISSUE TITLE
Text and tile edges

### ISSUE THREAD

**Issue by chebourne** [klokantech/tileserver-gl#347] opened 2019-02-07 14:32 UTC
Serving raster tiles via mapbox-gl:

    var map = new mapboxgl.Map({
        container: 'map',
        style: {
            "version": 8,
            "sources": {
                "raster-tiles": {
                    "type": "raster",
                    "url": "https://tileserver.johndoe.com/styles/osm-bright.json"
                }
            },
            "layers": [{
                "id": "mystyle",
                "type": "raster",
                "source": "raster-tiles",
                "minzoom": 0,
                "maxzoom": 22
            }]
        },
        center: [0,0],
        zoom: 3
    });

Why does the text get cutoff at tile edges - see meridian through London - this is using un-edited osm-bright style but seems to occur with any style?:

![image](https://user-images.githubusercontent.com/20801744/52418133-5137ce80-2ae5-11e9-9567-7634ca443868.png)

**Comment by chebourne** [comment] 2019-02-14 09:08
Solution has been covered in https://github.com/openmaptiles/openmaptiles/issues/224

Solution: No solution, use vector tiles.

**Comment by petrsloup** [comment] 2019-02-14 16:56
Duplicate of #344

**Closed by petrsloup** 2019-02-14 16:56 UTC
