### ISSUE TITLE
Need to change the value of "tiles" from auto generated 'osm2vectortiles.json'

### ISSUE THREAD

**Issue by bertrandmd** [klokantech/tileserver-gl#60] opened 2016-10-12 13:24 UTC
in my osm2vectortiles.json, i need to change the value of "tile"
ex:
"tiles": [
"127.0.0.1:8080/data/osm2vectortiles/{z}/{x}/{y}.pbf"
]

I need to have : 
"tiles": [
"127.0.0.1:8080/myfolder/data/osm2vectortiles/{z}/{x}/{y}.pbf"
]
with [tileserver doc](http://tileserver.readthedocs.io/en/latest/config.html) I can understand I need to create a config.json.
Could you be more precise about the minimum parameter to put in this file?

Thanks

**Comment by petrsloup** [comment] 2016-10-12 13:28
Changing the folder structure is not directly possible.

Additional software (such as nginx) is usually used in production in front of the tileserver-gl itself and is capable of handling this (see #51).

Duplicate of #51

**Closed by petrsloup** 2016-10-12 13:28 UTC

**Comment by klokan** [comment] 2016-10-12 14:08
To get started with the config file you can run tileserver gl with "--verbose" argument and it will print out the config automatically generated. This is a good starting point to copy it out, save it into a file and start to adjust it according to your needs.

**Comment by bertrandmd** [comment] 2016-10-12 15:16
@petrsloup yes nginx works ! thks
@klokan thks for the tips !
