### ISSUE TITLE
Qgis loading parameters

### ISSUE THREAD

**Issue by lorenzoperone** [klokantech/tileserver-gl#55] opened 2016-10-04 17:12 UTC
Hi,
I've installed the docker and loaded the mbtile of italy from http://osm2vectortiles.org/ from the web browser it seems to be all right, and I've tried to load the tms layer (http://192.168.99.100:32776/styles/basic-v9/{z}/{x}/{y}.png) in Qgis using the "Tile laye Plugin" (https://github.com/minorua/TileLayerPlugin) using this simple definition 

Italy basic http://192.168.99.100:32776/styles/basic-v9/{z}/{x}/{y}.png

in a text file (tsv).

I'd appreciate some tips to use it properly because in this way Qgis don't load the layer.
Thanks.
lorenzo

**Comment by lorenzoperone** [comment] 2016-10-06 12:32
Open the same issue on https://github.com/minorua/TileLayerPlugin/issues/23

**Comment by klokan** [comment] 2016-10-06 16:23
Why do you want to use the plugin?

WMTS standard is implemented in QGIS directly. TileServer GL gives you "WMTS" link.

Then follow this visual guide (for example):
https://tileserver.maptiler.com/#grandcanyon/qgis.guide

**Comment by klokan** [comment] 2016-10-06 16:24
Let us please know if this solve your problem - as I believe this ticket can be closed then.

**Comment by lorenzoperone** [comment] 2016-10-07 09:31
Hi Petr,
I've tried to load the WMTS directly in Qgis in Mac OS X and in Ubuntu with
italy.mbtile and the zurich.mbtile, in both the cases the WMTS link is a
bit strange, it's a remote link (
http://wmts.maptiler.com/aHR0cDovL2xvY2FsaG9zdDo4MDgwL3N0eWxlcy9iYXNpYy12OS9yZW5kZXJlZC5qc29u/wmts
).
Qgis seems to read the source but once loaded the layer nothing appears...
Thanks.
Lorenzo

Lorenzo Perone
twitter: @lorenzo_perone <https://twitter.com/lorenzo_perone>
photoblog: http://immagini.me


2016-10-06 18:24 GMT+02:00 Petr Pridal <notifications@github.com>:

**Comment by petrsloup** [comment] 2016-10-07 13:19
TileServer GL displays incorrect URL under the XYZ in index.html (see https://github.com/klokantech/tileserver-gl/issues/58#issuecomment-252249283)

Using `http://192.168.99.100:32776/styles/basic-v9/rendered/{z}/{x}/{y}.png` should work

Closing this as duplicate of #58

**Closed by petrsloup** 2016-10-07 13:19 UTC

**Comment by lorenzoperone** [comment] 2016-10-07 15:12
Hi Petr,
I’m not sure but I think that this link is not suitable for WMTS service

http://192.168.99.100:32776/styles/basic-v9/rendered/{z}/{x}/{y}.png

I’ve used it in Qgis but without any success.
Bye.
lorenzo

**Comment by lorenzoperone** [comment] 2016-10-11 09:39
@klokan could you give me a feedback about the above question?
Thanks.
lorenzo

**Comment by klokan** [comment] 2016-10-11 15:32
@lorenzoperone we have made a new release of the software.

Please upgrade your docker image to be sure to v1.1.4 (or newer in future).
This has a fixed bug in TileJSON.

The WMTS standard requires XML Metadata. The tiles are the same.

Our online service wmts.maptiler.com turns the TileJSON into WMTS GetCapabilities metadata. It runs only if the server is on public server address. Your server is on localhost - so it fails.

If you don't want to use our wmts.maptiler.com service - free free to create the XML file describing the WMTS capabilities yourself. You could also make a Pull Request to TileServer GL server code - which would generate the XML directly from our server - even offline or behind firewall.
We did not needed - so we have not done it (yet).

**Comment by lorenzoperone** [comment] 2016-10-13 08:22
Thanks @klokan , now is more clear.
I will try to pubblish the docker in a public virtual server to acquire the xml.
We (a group o [OSM Italy users](https://github.com/osmItalia)) are trying to configure a Rapsberry server for using as map server in emergency issues like the recent earthquake in center Italy, I'm involved also in the [terremotocentroitalia.info](http://terremotocentroitalia.info/) group.
The scope is a mesh wi-fi infrasctuture using [Ninux](http://wiki.ninux.org/) tecnology and a little unexpensive server to distribute maps developed by [HOT OSM team](http://osmit-tm.wmflabs.org/project/13).
We've made [some test](https://github.com/osmItalia/osm2vectortiles/blob/master/osm2vectortiles_on_RaspberryPI.md) with Osm2vectortile on Raspberry Pi 2 and in works like a charm.
Next (slow) steps I'd like to try with some friends (I'm not a developer) are:

- make an arm7 docker with tileserver-gl;
- test the docker on Raspberry Pi 3 with web istance and Qgis use.

I've talked about just for telling we appreciate a lot your work :)

Cc @aborruso @geofrizz

**Comment by klokan** [comment] 2016-10-13 15:45
That sounds as a very exciting project. Keep is informed, please! 👍

**Comment by jvalore** [comment] 2016-12-31 00:39
Hi Klokan
I am in the progress on evaluating an vector tile approach for a project and have previously used your maptiler program, so it was natural for me to look at the tilerserver-gl. 

I have it up and running (docker setup) on a local development machine and would like to try out the wmts part from QGIS/MapInfo etc. Could you elaborate a bit on 
>>
- free free to create the XML file describing the WMTS capabilities yourself. You could also make a Pull Request to TileServer GL server code - which would generate the XML directly from our server - even offline or behind firewall.
<<

I have tried to make a local xml file replacing the wmts.maptiler.com aspects with local ip aspect, but with no sucess.  

Thanks in advance. 

Br. 
John Valore
