### ISSUE TITLE
tileserver on https does not work in chrome due to mixed content request of http

### ISSUE THREAD

**Issue by hanobiwan** [klokantech/tileserver-gl#249] opened 2018-01-10 12:49 UTC
If you setup de tileserver-gl in docker on your own server for a https domain (with nginx and let's encrypt), the tilelayers are not shown due to Mixed Content.
> mapbox-gl.js:393 Mixed Content: The page at 'https://domainname.com/klokantech-basic/#8/50.545/4.376' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://domainname.com/data/v3.json'. This request has been blocked; the content must be served over HTTPS.

Is there a way to overcome this?

**Comment by petrsloup** [comment] 2018-01-11 10:28
You need to make sure to pass `X-Forwarded-Proto` to the container. See https://tileserver.readthedocs.io/en/latest/deployment.html#running-behind-a-proxy-or-a-load-balancer

Duplicate of #50, #165, #195

**Closed by petrsloup** 2018-01-11 10:28 UTC
