### ISSUE TITLE
tileserver-gl will not install on Windows

### ISSUE THREAD

**Issue by pkumar76** [klokantech/tileserver-gl#236] opened 2017-11-16 00:27 UTC
Hello:

We are trying to install tileserver-gl on Windows 7 and are getting errors. We have tried the following:

Windows 7
node 6.10.3
npm 3.10.10

**_npm install -g tileserver-gl-light installs perfectly fine._**

When entered npm install -g tileserver-gl the results we get are:

> @mapbox/mapbox-gl-native@3.5.4 preinstall C:\Users\pradeepv\AppData\Roaming\np
m\node_modules\.staging\@mapbox\mapbox-gl-native-45ebdc0d
> npm install node-pre-gyp

C:\Users\pradeepv\AppData\Roaming\npm
`-- node-pre-gyp@0.6.39

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\pradeepv\AppData\Roaming\npm\node_modules\.staging\@mapbo
x\mapbox-gl-native-45ebdc0d
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\pradeepv\AppData\Roamin
g\npm\node_modules\.staging\@mapbox\mapbox-gl-native-45ebdc0d'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pradeepv\AppData\Roaming\npm\node_modules\.staging\@mapbox
\mapbox-gl-native-45ebdc0d\npm-debug.log
C:\Users\pradeepv\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "tileserver-gl"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! @mapbox/mapbox-gl-native@3.5.4 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 4294963214
npm ERR!
npm ERR! Failed at the @mapbox/mapbox-gl-native@3.5.4 preinstall script 'npm ins
tall node-pre-gyp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @mapbox/mapbox-gl-nat
ive package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install node-pre-gyp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @mapbox/mapbox-gl-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @mapbox/mapbox-gl-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Software\tileserver\npm-debug.log
npm ERR! code 1

Any help or advice would be much appreciated.

**Comment by petrsloup** [comment] 2017-11-16 08:20
Duplicate of #76, #141.

The `tileserver-gl` does not support Windows

**Closed by petrsloup** 2017-11-16 08:20 UTC
